name: zknet-service Java CI with Maven & Deploy     #Actions name

on:
  push:
    branches:
      - dev       #dev branch

jobs:
  build:
    runs-on: ubuntu-latest    #runtime environment
    steps:
      - name: checkout
        uses: actions/checkout@v3   #checkout dev branch
        with:
          ref: 'dev'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1  # setup java env
        with:
          java-version: 1.8
#      - name: Set SSH Environment
#        run: |
#          mkdir -p ~/.ssh/
#          echo "${{ secrets.ACTION_DEPLOY_KEY }}" > ~/.ssh/id_rsa
#          echo "${{ secrets.ACTION_DEPLOY_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
#          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
#          chmod 600 ~/.ssh/id_rsa
#          chmod 700 ~/.ssh && chmod 700 ~/.ssh/*
#          ls -l ~/.ssh/
      - name: maven build
        run: mvn clean package -Pdev -B -e -U --file pom.xml
      - name: scp gateway to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.MY_ALIYUN_IP }}
          username: ${{ secrets.MY_ALIYUN_USER }}
          password: ${{ secrets.MY_ALIYUN_PASSWD }}
          port: 22
          source: "./gateway/target/zknet-gateway-dev.jar"
          target: "/application/zknet/gateway"
          strip_components: 2
          script: |
            mv /application/zknet/gateway/target/zknet-gateway-dev.jar /application/zknet/gateway/
      - name: start gateway
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.MY_ALIYUN_IP }}
          user: ${{ secrets.MY_ALIYUN_USER }}
          pass: ${{ secrets.MY_ALIYUN_PASSWD }}
          port: 22
          connect_timeout: 20s
          script: |
            cd /application/zknet/
            docker-compose restart zknet_gateway
#            cd /root/zknet-service/gateway/target/
#            i=`ps -ef|grep "zknet-gateway-dev"|grep java|grep -v grep|awk '{print $2}'`
#            while [ x$i != x ]; do
#              echo "kill $i"
#              kill $i
#              sleep 2s
#              i=`ps -ef|grep "zknet-gateway-dev"|grep java|grep -v grep|awk '{print $2}'`
#            done
#            nohup java -jar zknet-gateway-dev.jar --spring.profiles.active=dev > /dev/null  2>&1 &
